"""
Chat endpoints — Question answering with RAG and streaming.
"""

import uuid
from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from typing import Optional

from app.services.retriever import RetrieverService
from app.services.llm import LLMService
from app.services.chat_memory import ChatMemoryService

router = APIRouter()
retriever = RetrieverService()
llm = LLMService()
memory = ChatMemoryService()


class ChatRequest(BaseModel):
    question: str
    collection: str = "default"
    session_id: Optional[str] = None
    top_k: int = 5


class SourceChunk(BaseModel):
    document: str
    page: Optional[int] = None
    chunk: str
    relevance_score: float


class ChatResponse(BaseModel):
    answer: str
    sources: list[SourceChunk]
    session_id: str
    confidence: float


@router.post("/", response_model=ChatResponse)
async def chat(request: ChatRequest):
    """
    Ask a question about your documents.

    The system will:
    1. Search for relevant chunks using semantic similarity
    2. Build a prompt with the retrieved context
    3. Generate an answer grounded in the source documents
    4. Return the answer with source citations
    """
    session_id = request.session_id or str(uuid.uuid4())

    # Get conversation history for context
    history = memory.get_history(session_id, limit=5)

    # Retrieve relevant document chunks
    chunks = await retriever.search(
        query=request.question,
        collection=request.collection,
        top_k=request.top_k,
    )

    if not chunks:
        return ChatResponse(
            answer="I couldn't find any relevant information in the uploaded documents. "
                   "Please make sure you've uploaded documents to this collection.",
            sources=[],
            session_id=session_id,
            confidence=0.0,
        )

    # Build context from retrieved chunks
    context = "\n\n---\n\n".join([
        f"[Source: {c['metadata'].get('filename', 'unknown')}, "
        f"Page: {c['metadata'].get('page', 'N/A')}]\n{c['content']}"
        for c in chunks
    ])

    # Generate answer using LLM
    result = await llm.generate(
        question=request.question,
        context=context,
        chat_history=history,
    )

    # Save to conversation memory
    memory.add_message(session_id, "user", request.question)
    memory.add_message(session_id, "assistant", result["answer"])

    # Format sources
    sources = [
        SourceChunk(
            document=c["metadata"].get("filename", "unknown"),
            page=c["metadata"].get("page"),
            chunk=c["content"][:200] + "..." if len(c["content"]) > 200 else c["content"],
            relevance_score=round(c["score"], 3),
        )
        for c in chunks
    ]

    return ChatResponse(
        answer=result["answer"],
        sources=sources,
        session_id=session_id,
        confidence=round(result["confidence"], 2),
    )


@router.post("/stream")
async def chat_stream(request: ChatRequest):
    """
    Ask a question with streaming response (Server-Sent Events).
    Tokens are streamed as they're generated by the LLM.
    """
    session_id = request.session_id or str(uuid.uuid4())
    history = memory.get_history(session_id, limit=5)

    # Retrieve relevant chunks
    chunks = await retriever.search(
        query=request.question,
        collection=request.collection,
        top_k=request.top_k,
    )

    context = "\n\n---\n\n".join([
        f"[Source: {c['metadata'].get('filename', 'unknown')}]\n{c['content']}"
        for c in chunks
    ])

    async def generate():
        full_answer = ""
        async for token in llm.stream(
            question=request.question,
            context=context,
            chat_history=history,
        ):
            full_answer += token
            yield f"data: {token}\n\n"

        # Save to memory after streaming completes
        memory.add_message(session_id, "user", request.question)
        memory.add_message(session_id, "assistant", full_answer)
        yield "data: [DONE]\n\n"

    return StreamingResponse(generate(), media_type="text/event-stream")


@router.get("/history/{session_id}")
async def get_chat_history(session_id: str):
    """Get conversation history for a session."""
    history = memory.get_history(session_id)
    return {"session_id": session_id, "messages": history}
